<nav>

	<ul id="menu-demo2">
		<li><a href="<?php echo URL_SITE; ?>index.php?page=blog"><?php echo PILLMENU_1 ?></a>
		</li>
		<li><a href="<?php echo URL_SITE; ?>index.php?page=patro"><?php echo PILLMENU_2 ?></a>
		</li>
		<li><a href="<?php echo URL_SITE; ?>admin/index.php"><?php echo PILLMENU_3 ?></a>
		</li>
		<li><a href="<?php echo URL_SITE; ?>index.php?page=contact"><?php echo PILLMENU_4 ?></a>
		</li>

	</ul>

</nav>