<div class="sidebar1">

	<br>
	<br>

	<div id="cadremenu">

		<h1><?php echo ASIDE_ADMIN_1; ?></h1>

		<ul>
			<li><a href="ajout-article.php"><?php echo TITRE_RUB_ADMIN_0; ?></a></li>
			<li><a href="modif-articles.php"><?php echo TITRE_RUB_ADMIN_1; ?></a></li>
		</ul>

	</div>
	
	<br />
	<br />

		<div id="cadremenu">

		<h1><?php echo ASIDE_ADMIN_6; ?></h1>

		<ul>
			<li><a href="commentaires.php"><?php echo TITRE_RUB_ADMIN_12; ?></a></li>
		</ul>

	</div>

	<br />
	<br />

	<div id="cadremenu">

		<h1><?php echo ASIDE_ADMIN_2; ?></h1>

		<ul>
			<li><a href="effacer_gedcom.php"><?php echo TITRE_RUB_ADMIN_2; ?></a></li>
			<li><a href="select_gedcom.php"><?php echo TITRE_RUB_ADMIN_3; ?></a></li>
		</ul>

	</div>

	<br />
	<br />

	<div id="cadremenu">

		<h1><?php echo ASIDE_ADMIN_3; ?></h1>

		<ul>
			<li><a href="suppr_tables.php"><?php echo TITRE_RUB_ADMIN_4; ?></a></li>
			<li><a href="creation_tables.php"><?php echo TITRE_RUB_ADMIN_8; ?></a></li>
			<li><a href="tables_demo.php"><?php echo TITRE_RUB_ADMIN_13; ?></a></li>
			<li><a href="tailledb.php"><?php echo TITRE_RUB_ADMIN_9; ?></a></li>
		</ul>

	</div>

	<br />
	<br />

	<div id="cadremenu">

		<h1><?php echo ASIDE_ADMIN_4; ?></h1>

		<ul>
			<li><a href="modules_blog.php"><?php echo TITRE_RUB_ADMIN_5; ?></a></li>
			<li><a href="modules_genealogie.php"><?php echo TITRE_RUB_ADMIN_6; ?></a></li>
			<li><a href="options.php"><?php echo TITRE_RUB_ADMIN_7; ?></a></li>
			<li><a href="meta.php"><?php echo TITRE_RUB_ADMIN_11; ?></a></li>
		</ul>

	</div>

	<br />
	<br />

	<div id="cadremenu">

		<h1><?php echo ASIDE_ADMIN_5; ?></h1>

		<ul>
			<li><a href="membres.php"><?php echo TITRE_RUB_ADMIN_10; ?></a></li>
		</ul>

	</div>
	
</div>