
-- --------------------------------------------------------

--
-- Table structure for table `individus`
--

CREATE TABLE `individus` (
  `id` int(11) NOT NULL,
  `ref` varchar(11) NOT NULL,
  `nom` varchar(100) DEFAULT NULL,
  `prenom` varchar(100) DEFAULT NULL,
  `sex` varchar(5) DEFAULT NULL,
  `surname` varchar(100) NOT NULL,
  `note` varchar(500) NOT NULL,
  `public` tinyint(1) NOT NULL,
  `filiation` varchar(100) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `individus`
--

INSERT INTO `individus` (`id`, `ref`, `nom`, `prenom`, `sex`, `surname`, `note`, `public`, `filiation`) VALUES
(1, '3I', 'Alain/AMAND/\r\n', 'Alain\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(2, '7I', 'Albert Abélard/AMAND/\r\n', 'Albert Abélard\r\n', 'M\r\n', 'AMAND\r\n', 'Il est cité comme retraité en 1960.\r\n', 0, ''),
(3, '9I', 'Bronislawa/MIZERA/\r\n', 'Bronislawa\r\n', 'F\r\n', 'MIZERA\r\n', '', 0, ''),
(4, '23I', 'Hoche Gaston Blomy/AMAND/\r\n', 'Hoche Gaston Blomy\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(5, '27I', 'Germaine/THIERY/\r\n', 'Germaine\r\n', 'F\r\n', 'THIERY\r\n', '', 0, ''),
(6, '34I', 'Blomy Abélard/AMAND/\r\n', 'Blomy Abélard\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(7, '38I', 'Adeline/DESPLANQUES/\r\n', 'Adeline\r\n', 'F\r\n', 'DESPLANQUES\r\n', '', 0, ''),
(8, '45I', 'Blomé Adolphe/AMAND/\r\n', 'Blomé Adolphe\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(9, '48I', 'Hortense Caroline/FERNEZ/\r\n', 'Hortense Caroline\r\n', 'F\r\n', 'FERNEZ\r\n', '', 0, ''),
(10, '72I', '(Georges) Florentin Guillaume/AMAND/\r\n', '(Georges) Florentin Guillaume\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(11, '76I', 'Pauline/BLANCART/\r\n', 'Pauline\r\n', 'F\r\n', 'BLANCART\r\n', '', 0, ''),
(12, '92I', 'François Joseph/AMAND/\r\n', 'François Joseph\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(13, '94I', 'Augustine/DAPSENCE/\r\n', 'Augustine\r\n', 'F\r\n', 'DAPSENCE\r\n', '', 0, ''),
(14, '108I', 'Georges/AMAND/\r\n', 'Georges\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(15, '114I', 'Gabrielle/FENEULLE/\r\n', 'Gabrielle\r\n', 'F\r\n', 'FENEULLE\r\n', '', 0, ''),
(16, '117I', 'Charles Marie/AMAND/\r\n', 'Charles Marie\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(17, '120I', 'Jean/GUEROT/\r\n', 'Jean\r\n', 'M\r\n', 'GUEROT\r\n', '', 0, ''),
(18, '123I', 'Augustine Fidèle/AMAND/\r\n', 'Augustine Fidèle\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(19, '125I', 'Fidel Joseph/AMAND/\r\n', 'Fidel Joseph\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(20, '128I', 'Gabriel Joseph Fidel/AMAND/\r\n', 'Gabriel Joseph Fidel\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(21, '133I', 'Apoline Françoise Joseph/TRUFFIN/\r\n', 'Apoline Françoise Joseph\r\n', 'F\r\n', 'TRUFFIN\r\n', '', 0, ''),
(22, '140I', 'Nicolas François/AMAND/\r\n', 'Nicolas François\r\n', 'M\r\n', 'AMAND\r\n', 'il serait originaire de Condé sur Escaut\r\n', 0, ''),
(23, '142I', 'Anne Catherine/CHOQUET/\r\n', 'Anne Catherine\r\n', 'F\r\n', 'CHOQUET\r\n', '', 0, ''),
(24, '151I', 'Jean-Baptiste/FENEULLE/\r\n', 'Jean-Baptiste\r\n', 'M\r\n', 'FENEULLE\r\n', '', 0, ''),
(25, '153I', 'Marguerite Joseph/BLASSEAU/\r\n', 'Marguerite Joseph\r\n', 'F\r\n', 'BLASSEAU\r\n', '', 0, ''),
(26, '167I', 'Nicolas/TRUFFIN/\r\n', 'Nicolas\r\n', 'M\r\n', 'TRUFFIN\r\n', '', 0, ''),
(27, '170I', '/PISSON/\r\n', NULL, 'F\r\n', 'PISSON\r\n', '', 0, ''),
(28, '175I', 'Louis Joseph/DUMONT/\r\n', 'Louis Joseph\r\n', 'M\r\n', 'DUMONT\r\n', '', 0, ''),
(29, '179I', 'Jean-Baptiste/POSIERE/\r\n', 'Jean-Baptiste\r\n', 'M\r\n', 'POSIERE\r\n', '', 0, ''),
(30, '183I', 'Marie Magdelaine/AMERSE/\r\n', 'Marie Magdelaine\r\n', 'F\r\n', 'AMERSE\r\n', '', 0, ''),
(31, '186I', 'Louis/WERY/\r\n', 'Louis\r\n', 'M\r\n', 'WERY\r\n', '', 0, ''),
(32, '191I', 'André/AMAND/\r\n', 'André\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(33, '193I', 'Marie/RASEZ/\r\n', 'Marie\r\n', 'F\r\n', 'RASEZ\r\n', '', 0, ''),
(34, '196I', 'Thomas/CHOQUET/\r\n', 'Thomas\r\n', 'M\r\n', 'CHOQUET\r\n', '', 0, ''),
(35, '198I', 'Marie Anne/BROSSART/\r\n', 'Marie Anne\r\n', 'F\r\n', 'BROSSART\r\n', '', 0, ''),
(36, '206I', 'Anne Marie Joseph/AMAND/\r\n', 'Anne Marie Joseph\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(37, '209I', 'Jean François Joseph/TELLIER/\r\n', 'Jean François Joseph\r\n', 'M\r\n', 'TELLIER\r\n', '', 0, ''),
(38, '215I', 'Jean Joseph/AMAND/\r\n', 'Jean Joseph\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(39, '218I', 'Marie Suzanne/PICART/\r\n', 'Marie Suzanne\r\n', 'F\r\n', 'PICART\r\n', '', 0, ''),
(40, '222I', 'Jean-Baptiste/AMAND/\r\n', 'Jean-Baptiste\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(41, '224I', 'Marie Magdelaine Joseph/AMAND/\r\n', 'Marie Magdelaine Joseph\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(42, '226I', 'Marie Eugénie Joseph/AMAND/\r\n', 'Marie Eugénie Joseph\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(43, '228I', 'Catherine Joseph/AMAND/\r\n', 'Catherine Joseph\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(44, '230I', 'Adorateur Joseph/AMAND/\r\n', 'Adorateur Joseph\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(45, '232I', 'François Théodore/AMAND/\r\n', 'François Théodore\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(46, '234I', 'Julie Eugénie/AMAND/\r\n', 'Julie Eugénie\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(47, '240I', 'Fernande Adeline/AMAND/\r\n', 'Fernande Adeline\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(48, '247I', 'Joseph/WADIN/\r\n', 'Joseph\r\n', 'M\r\n', 'WADIN\r\n', '', 0, ''),
(49, '250I', 'Charlemagne/DEGAGE/\r\n', 'Charlemagne\r\n', 'M\r\n', 'DEGAGE\r\n', '', 0, ''),
(50, '258I', 'Pierre/MACHECOURT/\r\n', 'Pierre\r\n', 'M\r\n', 'MACHECOURT\r\n', '', 0, ''),
(51, '262I', 'Léon/DREYFUS/\r\n', 'Léon\r\n', 'M\r\n', 'DREYFUS\r\n', '', 0, ''),
(52, '264I', 'Marceau/AMAND/\r\n', 'Marceau\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(53, '266I', 'Odette/TATINCLAUX/\r\n', 'Odette\r\n', 'F\r\n', 'TATINCLAUX\r\n', '', 0, ''),
(54, '293I', 'Elisabeth/DESHAYES/\r\n', 'Elisabeth\r\n', 'F\r\n', 'DESHAYES\r\n', '', 0, ''),
(55, '297I', 'Xavier/DISANT/\r\n', 'Xavier\r\n', 'M\r\n', 'DISANT\r\n', '', 0, ''),
(56, '301I', 'Joseph Charles/GILBERT/\r\n', 'Joseph Charles\r\n', 'M\r\n', 'GILBERT\r\n', '', 0, ''),
(57, '312I', 'François/DE BUCHY/\r\n', 'François\r\n', 'M\r\n', 'DE BUCHY\r\n', '', 0, ''),
(58, '325I', 'Augustin/DERVAL/\r\n', 'Augustin\r\n', 'M\r\n', 'DERVAL\r\n', '', 0, ''),
(59, '329I', 'François/PAGNIEZ/\r\n', 'François\r\n', 'M\r\n', 'PAGNIEZ\r\n', '', 0, ''),
(60, '333I', 'Quentin/SORLIN/\r\n', 'Quentin\r\n', 'M\r\n', 'SORLIN\r\n', '', 0, ''),
(61, '341I', 'Henri/THIERY/\r\n', 'Henri\r\n', 'M\r\n', 'THIERY\r\n', '', 0, ''),
(62, '344I', 'Anna/NAUTET/\r\n', 'Anna\r\n', 'F\r\n', 'NAUTET\r\n', '', 0, ''),
(63, '356I', 'Jean Baptiste/THIERY/\r\n', 'Jean Baptiste\r\n', 'M\r\n', 'THIERY\r\n', '', 0, ''),
(64, '360I', 'Louis/THIERY/\r\n', 'Louis\r\n', 'M\r\n', 'THIERY\r\n', '', 0, ''),
(65, '364I', 'Germain/THIERY/\r\n', 'Germain\r\n', 'M\r\n', 'THIERY\r\n', '', 0, ''),
(66, '367I', 'Arthur/THIERY/\r\n', 'Arthur\r\n', 'M\r\n', 'THIERY\r\n', '', 0, ''),
(67, '370I', 'Virginie/THIERY/\r\n', 'Virginie\r\n', 'F\r\n', 'THIERY\r\n', '', 0, ''),
(68, '373I', 'Alphonse/THIERY/\r\n', 'Alphonse\r\n', 'M\r\n', 'THIERY\r\n', '', 0, ''),
(69, '402I', 'Marie Aimée Joséphine/AMAND/\r\n', 'Marie Aimée Joséphine\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(70, '406I', 'Etienne Victor Joseph/CALOTTE/\r\n', 'Etienne Victor Joseph\r\n', 'M\r\n', 'CALOTTE\r\n', '', 0, ''),
(71, '427I', 'Alexandre Joseph Fidel/AMAND/\r\n', 'Alexandre Joseph Fidel\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(72, '433I', 'Nicolas Joseph/AMAND/\r\n', 'Nicolas Joseph\r\n', 'M\r\n', 'AMAND\r\n', '', 0, ''),
(73, '435I', 'Fidèle Véronique/TELLIER/\r\n', 'Fidèle Véronique\r\n', 'F\r\n', 'TELLIER\r\n', '', 0, ''),
(74, '438I', 'Henri Joseph/DAPSENCE/\r\n', 'Henri Joseph\r\n', 'M\r\n', 'DAPSENCE\r\n', '', 0, ''),
(75, '439I', 'Marie Anne Joseph/FENEUILLE/\r\n', 'Marie Anne Joseph\r\n', 'F\r\n', 'FENEUILLE\r\n', '', 0, ''),
(76, '445I', 'Anne Catherine/AMAND/\r\n', 'Anne Catherine\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(77, '451I', 'Jean Baptiste/DAPSENCE/\r\n', 'Jean Baptiste\r\n', 'M\r\n', 'DAPSENCE\r\n', '', 0, ''),
(78, '453I', 'Anne Marie/AMAND/\r\n', 'Anne Marie\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(79, '456I', 'Joséphine Adélaïde Joseph/AMAND/\r\n', 'Joséphine Adélaïde Joseph\r\n', 'F\r\n', 'AMAND\r\n', '', 0, ''),
(80, '462I', 'Henri Joseph Albert/DARTOIS/\r\n', 'Henri Joseph Albert\r\n', 'M\r\n', 'DARTOIS\r\n', '', 0, ''),
(81, '466I', 'Jacques Joseph/DARTOIS/\r\n', 'Jacques Joseph\r\n', 'M\r\n', 'DARTOIS\r\n', '', 0, ''),
(82, '468I', 'Anne Marie Françoise/SENECAUX/\r\n', 'Anne Marie Françoise\r\n', 'F\r\n', 'SENECAUX\r\n', '', 0, ''),
(83, '474I', 'Lucie/DARTOIS/\r\n', 'Lucie\r\n', 'F\r\n', 'DARTOIS\r\n', '', 0, '');
